"""
配置模块：环境变量读取、路径常量、System Prompt 模板。

主要配置文件：settings.py
"""

from config.settings import (
    # 路径配置
    SCRIPT_DIR,
    DEFAULT_HISTORY,
    DEFAULT_REMINDERS,
    # RAG 配置
    RAG_KB_DIR,
    RAG_INDEX_PATH,
    EXTERNAL_KB_DIR,
    TRAIN_EXTERNAL_KB_DIR,
    BGE_MODEL_PATH,
    RAG_ENABLED,
    RAG_TOP_K,
    RAG_MIN_SCORE,
    RAG_MAX_CONTEXT_LEN,
    RAG_CONTEXT_TEMPLATE,
    # 本地模型配置
    MODEL_PATH,
    LORA_PATH,
    MERGED_MODEL_PATH,
    LOCAL_MODEL_TEMPERATURE,
    LOCAL_MODEL_TOP_P,
    LOCAL_MODEL_MAX_TOKENS,
    USE_LOCAL_MODEL,
    # 主动提问配置
    CHAT_HISTORY_PATH,
    INTERVAL_SECONDS,
    SESSION_COOLDOWN_SECONDS,
    SESSION_IDLE_TIMEOUT_SECONDS,
    FORCE_ASK_AFTER_COOLDOWN,
    USE_TOPIC_EXIT_MODEL,
    # 提醒系统配置
    REMINDERS_PATH,
    REMINDER_AHEAD_SECONDS,
    # System Prompt 配置
    DECISION_SYSTEM,
    CARING_SYSTEM,
    QUESTION_SYSTEM,
    CHAT_SESSION_SYSTEM,
    TOPIC_EXIT_SYSTEM,
    BIRTHDAY_GREETING_SYSTEM,
    EVENT_REMINDER_SYSTEM,
    EVENT_EXTRACTION_SYSTEM,
    # 用户主动说话配置
    USER_STATE_PATH,
    USER_ACTIVE_THRESHOLD,
    ADAPTIVE_INTERVAL,
    MAX_CONSECUTIVE_PROACTIVE,
    ACTIVITY_INTERVAL_MULTIPLIERS,
)

__all__ = [
    # 路径配置
    "SCRIPT_DIR",
    "DEFAULT_HISTORY",
    "DEFAULT_REMINDERS",
    # RAG 配置
    "RAG_KB_DIR",
    "RAG_INDEX_PATH",
    "EXTERNAL_KB_DIR",
    "TRAIN_EXTERNAL_KB_DIR",
    "BGE_MODEL_PATH",
    "RAG_ENABLED",
    "RAG_TOP_K",
    "RAG_MIN_SCORE",
    "RAG_MAX_CONTEXT_LEN",
    "RAG_CONTEXT_TEMPLATE",
    # 本地模型配置
    "MODEL_PATH",
    "LORA_PATH",
    "MERGED_MODEL_PATH",
    "LOCAL_MODEL_TEMPERATURE",
    "LOCAL_MODEL_TOP_P",
    "LOCAL_MODEL_MAX_TOKENS",
    "USE_LOCAL_MODEL",
    # 主动提问配置
    "CHAT_HISTORY_PATH",
    "INTERVAL_SECONDS",
    "SESSION_COOLDOWN_SECONDS",
    "SESSION_IDLE_TIMEOUT_SECONDS",
    "FORCE_ASK_AFTER_COOLDOWN",
    "USE_TOPIC_EXIT_MODEL",
    # 提醒系统配置
    "REMINDERS_PATH",
    "REMINDER_AHEAD_SECONDS",
    # System Prompt 配置
    "DECISION_SYSTEM",
    "CARING_SYSTEM",
    "QUESTION_SYSTEM",
    "CHAT_SESSION_SYSTEM",
    "TOPIC_EXIT_SYSTEM",
    "BIRTHDAY_GREETING_SYSTEM",
    "EVENT_REMINDER_SYSTEM",
    "EVENT_EXTRACTION_SYSTEM",
    # 用户主动说话配置
    "USER_STATE_PATH",
    "USER_ACTIVE_THRESHOLD",
    "ADAPTIVE_INTERVAL",
    "MAX_CONSECUTIVE_PROACTIVE",
    "ACTIVITY_INTERVAL_MULTIPLIERS",
]
